name: EC2 Provision

on:

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ec2

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Debug OIDC token
        run: |
         curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
         "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" \
          | jq -r '.value' | cut -d '.' -f2 | base64 -d 2>/dev/null | jq .

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=ec2.tfplan
        env:
          TF_VAR_ami_id: ${{ vars.EC2_AMI_ID }}

      - name: Terraform Apply
        run: terraform apply -auto-approve ec2.tfplan
